name: k3dziomo

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  setup-k3d:
    steps:
      - name: install brew
        run: brew install wget
      - name: k3d install
        run: brew install k3d
      - name: check up
        run: |
          k3d --version
          k3d cluster create my-cluster
          k3d cluster list
          echo dziala :3
      
           
