name: k3dziomo

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install k3d
        run: wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      - name: create cluster
        run: k3d cluster create my-cluster
      - name: checkup
        run: |
           k3d cluster list
           kubectl get pods -A
      - name: make deploy
        run: kubectl apply -f httpbin-deployment.yaml
      - name:
        run: |
           kubectl get deploy -A
           kubectl get pods -A
           kubectl get svc -A
