name: Detect YAML Changes
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  detect-repo-changes:
    name: Detect repo changes
    runs-on: ubuntu-latest
    outputs:
      yaml-changed: ${{ steps.changes.outputs.repo }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Detect YAML changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            repo:
              - 'configs/*.yaml'
        